spring:
  profiles:
    active: ${env}
  application:
    name: user
  # redis
#  redis:
#    host: 39.104.96.141
#    port: 8379
#    password:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 9090

# logging
logging:
  path:
    classpath: logback-spring.xml

#自定义参数
saltEncrypt: 123
serverConfigHost:
skipRemoteHost: dev