# 开发环境配置

#服务器配置
server:
  address: 0.0.0.0
  port: 8070

swaggerUrl:
  39.104.52.84
#  vancem.s1.natapp.cc
#SSH_USER:
#  root
#SSH_PASSWORD:
#  Kong198818
#SSH_REMOTE_SERVER:
#  39.104.52.84
#MYSQL_REMOTE_SERVER:
#  39.104.52.84