# 开发环境配置

#服务器配置
server:
  address: 0.0.0.0
  port: 70

swaggerUrl:
  218.2.177.210:70
#SSH_USER:
#  root
#SSH_PASSWORD:
#  Kong198818
#SSH_REMOTE_SERVER:
#  39.104.52.84
#MYSQL_REMOTE_SERVER:
#  39.104.52.84