spring:
  profiles:
    active: ${env}
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8070
  context-path: /
logging:
  file: manage.log
shiro:
  loginUrl: /login.html

#  自定义
saltEncrypt: 123
accessKeyId: LTAIceTyFAv3wFbS
accessKeySecret: k6DqH7zUE0JFyjuroCasU2dIDI1Fxl
bucketUrl: oss-cn-hangzhou.aliyuncs.com
bucketName: idcfota
skipRemoteHost: pro
defaultPassWord: 123456

weather.key: 33489
weather.sign: a423a10ccfdfaaf60c4674dc48d06356

env: dev
mybatis.configuration.cache-enabled: false

